# Generated by Django 5.2.14 on 2026-05-29 18:27

import apps.core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import zeraora.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=zeraora.uuid.uuid7, editable=False, unique=True, verbose_name='用户唯一ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
                ('is_superuser', models.BooleanField(default=False, help_text='指无须显式分配即可拥有所有权限', verbose_name='是超级管理员')),
                ('is_staff', models.BooleanField(default=False, help_text='用户是否可以登录管理站点。', verbose_name='是管理员')),
                ('is_active', models.BooleanField(default=True, help_text='用标记删除取代物理删除。', verbose_name='未注销')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='名称')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓氏')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('groups', models.ManyToManyField(blank=True, help_text='用户自动获得每个组的所有权限。', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='用户拥有的所有权限。', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='权限集')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('members', apps.core.models.ActiveUserManger()),
            ],
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=32, verbose_name='微信用户 OpenID')),
                ('unionid', models.CharField(blank=True, max_length=32, verbose_name='微信用户 UnionID')),
                ('session', models.CharField(blank=True, max_length=32, verbose_name='微信用户 Session Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'core_wechat_user',
            },
        ),
    ]
