# Generated by Django 5.2.14 on 2026-05-28 09:27

import apps.core.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('members', apps.core.models.ActiveUserManger()),
            ],
        ),
    ]
