# Generated by Django 5.2.14 on 2026-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=32, verbose_name='微信用户 OpenID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_session',
            field=models.CharField(blank=True, max_length=32, verbose_name='微信用户 Session Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_unionid',
            field=models.CharField(blank=True, max_length=32, verbose_name='微信用户 UnionID'),
        ),
    ]
